Feature/styling
leonardodiasb/bookstore pull request #4
Opened 2021-08-27 20:42 UTC by leonardodiasb

- Used CSS to style the page based on the Bookstore CMS project page on Zeplin.

2021-08-27 22:12 UTC, ZawadiSumba66 requested changes
Hi @leonardodiasb 👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-27 22:12 UTC, ZawadiSumba66 commented on src/components/Navbar.js
> +      <h1 className="logo">Bookstore CMS</h1>
- [x] The bookstore and the cms words ought to appear in one line. Kindly fix this.

2021-08-27 22:12 UTC, ZawadiSumba66 commented on src/components/Navbar.js
>            <li key={link.id} className="nav-li">
- [x] The books link in the navbar has a darker shade than the categories link to the right of it as you can see below:
![image](https://user-images.githubusercontent.com/68167810/131191076-bdd69fc7-eaf9-4229-b813-e50f42b1a40a.png)

2021-08-27 22:12 UTC, ZawadiSumba66 commented on src/components/books/Book.js
> +        <span className="Percent-Complete">0%</span>
- [x] The progress chart to the left of the percentage number is currently missing while displaying a book like the one as follows:
![image](https://user-images.githubusercontent.com/68167810/131192150-a91a52f3-7d6c-4efa-8d72-1c81cec9aecb.png)

2021-08-27 22:12 UTC, ZawadiSumba66 commented on src/components/books/InputBook.js
> +      <button className="add-btn" type="submit">ADD BOOK</button>
- [x] Kindly ensure that the book, author inputs, and the add button are all inline. The add and author input should not overflow to the next line. 
- [x] Also ensure that the background color for the inputs is white. 
- [x] I would also urge to try and add some margin below the form.
- [ ] Check the screenshots below for comparison in accordance to the above suggestions:
yours:
![image](https://user-images.githubusercontent.com/68167810/131192924-412d951b-407d-4549-9ed4-57dabb9f79fd.png)
=======================================================================
template's
![image](https://user-images.githubusercontent.com/68167810/131192995-971ec3d0-b5c1-4a83-8246-bc37b6d8d123.png)

2021-08-27 22:12 UTC, ZawadiSumba66 commented on src/index.css
> +nav {
- [ ] There is a bit of redundant code in your CSS file. You could reduce this by adding a common class where a particular class applies to different JSX tags.
For example  
+ font-stretch: normal;
+  font-style: normal;
+  line-height: normal;
+  font-family: Montserrat, sans-serif; and a lot more selectors.
You can check [this article for support](https://speckyboy.com/good-bad-css-practices/)

2021-08-28 01:32 UTC, mricanho requested changes
Hi @leonardodiasb ! 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## **[- NOTE FOR THE NEXT REVIEWER -]**

**As long as I can see, he did all the fixes, and the only thing left is the linters, please take it in consideration and approve this project if all the linters pass**

![attention](https://user-images.githubusercontent.com/60631456/131202026-094d1b4e-3e0d-4ffb-b17c-4a352506d07d.gif)

 ## Required Changes ♻️

- [ ] Please, double-check the linters, you have some errors from your last change, remember that all the linters must pass in order to approve this project.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-28 12:36 UTC, AshakaE approved these changes
### Hi @leonardodiasb  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-28 13:21 UTC, merged